name: desplega.ai action
description: Run desplega.ai test suites and receive real-time results
author: desplega.ai

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: green

# Define your inputs here.
inputs:
  apiKey:
    description: API key for authentication
    required: true
  originUrl:
    description: Base URL for the API
    required: false
    default: 'https://api.desplega.ai'
  suiteIds:
    description: List of suite IDs to run (comma-separated)
    required: false
  failFast:
    description: Whether to stop on first failure
    required: false
    default: 'false'
  block:
    description: Whether to block execution
    required: false
    default: 'false'
  maxRetries:
    description:
      Maximum number of retries for the trigger call (0 disables retries)
    required: false
    default: '0'

# Define your outputs here.
outputs:
  runId:
    description: The ID of the run
  status:
    description:
      'The final status of the run: passed, failed, error, running, skipped'

runs:
  using: node20
  main: dist/index.js
